language: node_js
node_js:
    - "8"
    - "9"
    - "10"
python:
  - '3.6'
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"
services:
    - mongodb
    - redis-server
    - docker
cache:
    directories:
        - node_modules
install:
  - npm install
  - pip3 install awscli ecs-deploy
script:
    - npm run build
    - npm run test
deploy:
  - provider: script
    script: ./scripts/deploy.sh
    on:
        branch: feature/work-sample
