sudo: required
language: node_js
node_js:
    - "8"
    - "9"
    - "10"
python:
  - '3.5'
services:
    - mongodb
    - redis-server
    - docker
cache:
    directories:
        - node_modules
install:
  - npm install
  - sudo $(which pip) install ecs-deploy
script:
    - npm run build
    - npm run test
deploy:
  - provider: script
    script: ./scripts/deploy.sh
    on:
        branch: feature/work-sample
