sudo: false
language: node_js
node_js:
    - "8"
    - "9"
    - "10"
python:
  - '3.5'
services:
    - mongodb
    - docker
cache:
    directories:
        - node_modules
script:
    - npm run build
    - npm run test
install:
  - sudo pip3 install ecs-deploy
deploy:
  - provider: script
    script: ./scripts/deploy.sh
    on:
        branch: feature/work-sample
