environment           = "dev"
cluster_name          = "typescript-node-starter-dev"
project               = "typescript-node"
app                   = "starter"
health_check          = "/health"
domain                = "sandbox.eha.im"
url                   = "typescript-node-starter"
application_memory    = "512"
http_rule_priority    = "1"
redis_engine_version  = "5.0.4"
elasticache_node_type = "cache.t2.micro"
MONGODB_URI           = "mongodb+srv://prod-user:secret123@typescript-node-starter-x5usm.mongodb.net/test?retryWrites=true&w=majority"
SESSION_SECRET        = "ldsofiosdiofisodiosfosdifsoo"
FACEBOOK_ID           = "754220301289665"
FACEBOOK_SECRET       = "41860e58c256a3d7ad8267d3c1939a4a"
public_key            = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDv0Zn1t/Rpqtc3DhXrP3d1c1i4d8YKBSb+FGvu10LUgFv/dooPPdKFhi7r2jfjxW4TwDEBNmZNy1BFhfubVyHjmJpTnnb84OJUAbGKWDoL3WS/dxDlzGFf3u9W08FlEmWmqT0Q0WXuXj+317CnWkXcNE5k2qMABP7FJoWLacTHFo3Qt4V875Wm+88JonI6yXnVdeDoRW8gPRV25b0FMitIF9M4ORve7uq+dCo6L/UspMnVwjV2R1vCoGHz7c8V1PwJ/cWMdAMHEdO3HARBogZo/gfotR6uzaDUTDrZR7QJQ6YPSB30Id2Vtz5D1ugeSVdOXHvVfuip3WDpN7GtwGS5 oluwafemi.olofintuyi@gmail.com"
